// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDUhUeGvPPHIddpW6bWSTznBsrdI5GHL-U',
    appId: '1:878587191576:android:d1d6afc162cfd6318afe6d',
    messagingSenderId: '878587191576',
    projectId: 'techpay-wallet',
    storageBucket: 'techpay-wallet.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDGMUV7_d7b1oSTqk6JcqqHEMXnNdcgkfo',
    appId: '1:878587191576:web:70feacbc6ee701d58afe6d',
    messagingSenderId: '878587191576',
    projectId: 'techpay-wallet',
    authDomain: 'techpay-wallet.firebaseapp.com',
    storageBucket: 'techpay-wallet.firebasestorage.app',
    measurementId: 'G-XLSXQCZEGN',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAawJQswbwEJmAs827Txy1BLiIVvQj4HL4',
    appId: '1:878587191576:ios:d9bbd6b91ca0c5fb8afe6d',
    messagingSenderId: '878587191576',
    projectId: 'techpay-wallet',
    storageBucket: 'techpay-wallet.firebasestorage.app',
    iosBundleId: 'com.example.techpayApp',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAawJQswbwEJmAs827Txy1BLiIVvQj4HL4',
    appId: '1:878587191576:ios:d9bbd6b91ca0c5fb8afe6d',
    messagingSenderId: '878587191576',
    projectId: 'techpay-wallet',
    storageBucket: 'techpay-wallet.firebasestorage.app',
    iosBundleId: 'com.example.techpayApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDGMUV7_d7b1oSTqk6JcqqHEMXnNdcgkfo',
    appId: '1:878587191576:web:b8c85111341a4ecb8afe6d',
    messagingSenderId: '878587191576',
    projectId: 'techpay-wallet',
    authDomain: 'techpay-wallet.firebaseapp.com',
    storageBucket: 'techpay-wallet.firebasestorage.app',
    measurementId: 'G-E275C4ZNMH',
  );

}